import Head from "next/head";
import { Inter } from "@next/font/google";
import { AiOutlinePlus } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>ToDo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/headicon.jpg" />
      </Head>
      <div className="h-screen w-screen p-4 bg-gradient-to-r from-[#7A918D] to [#99C2A2]">
        {/* container */}
        <div>
          <h3>To Do App</h3>
          <form>
            <input type="text" placeholder="Add To Do"></input>
            <button>
              <AiOutlinePlus size={30} />
            </button>
          </form>
        </div>
      </div>
    </div>
  );
}
